services:
  - type: web
    name: chatify
    runtime: node
buildCommand: npm install --prefix backend && cd frontend && NPM_CONFIG_PRODUCTION=false npm install && npm run build
startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://chatify-qiuc.onrender.com
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_FROM_NAME
        value: Chatify
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        sync: false
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: ARCJET_KEY
        sync: false
